name: DeathMessages
version: ${project.version}
main: net.joshb.deathmessages.DeathMessages
api-version: 1.17
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
author: Joshb_
commands:
  deathmessages:
    description: Main plugin command
    aliases: [dm]
  deathmessagestoggle:
    description: Alias for /dm toggle in one command
    aliases: [dmt, dmtoggle]